#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base

WORKDIR /app
EXPOSE 80
EXPOSE 443

COPY dist/apps/Backend .

FROM base AS final
WORKDIR /app
ENTRYPOINT ["dotnet", "DockerMfe.Backend.dll"]
